### ISSUE TITLE
React-redux not working with electron-webpack

### ISSUE THREAD

**Issue by shahkeyur** [electron-userland/electron-webpack#349] opened 2020-02-13 03:51 UTC
I am not sure if this is the right place to open this issue.

My old project was using react-scripts initially, but it was limited for electron app.I am noob when it comes down to webpack. So I replaced it with electron-webpack. It has the same react code but it doesn't work when I run it with electron-webpack.

 I've been dealing with this issue for more than a week and so far I just know that this error is because of  react-redux or may be something I am missing, I've no clue and this is really annoying error. If I remove everything from main component(e.g. Store, Routes) it works but I add store again it gives me error. I am not using any .babelrc. 

Please someone help me.

Thanks in advance.

This are the packages I am using.  

   ```
"devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/preset-react": "^7.8.3",
    "concurrently": "^4.1.2",
    "devtron": "^1.4.0",
    "electron": "^7.1.9",
    "electron-builder": "^21.2.0",
    "electron-webpack": "^2.7.4",
    "electron-webpack-eslint": "^5.0.1",
    "eslint-plugin-import": "2.17.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "node-sass": "^4.13.0",
    "sass-loader": "^8.0.2",
    "typescript": "^3.7.5",
    "wait-on": "^3.3.0",
    "webpack": "^4.41.5"
  },
  "dependencies": {
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@sentry/electron": "^1.2.0",
    "@types/jquery": "^3.3.32",
    "@types/node": "^13.7.1",
    "@types/react": "^16.9.19",
    "@types/react-dom": "^16.9.5",
    "autobind-decorator": "^2.4.0",
    "axios": "^0.18.1",
    "bootstrap": "^4.4.1",
    "classnames": "^2.2.6",
    "cross-env": "^5.2.1",
    "crypto-js": "^3.1.9-1",
    "dotenv": "^8.2.0",
    "electron-is-dev": "^1.1.0",
    "electron-log": "^4.0.3",
    "electron-progressbar": "^1.2.0",
    "electron-reload": "^1.5.0",
    "electron-splashscreen": "^1.0.0",
    "electron-updater": "^4.2.0",
    "eslint": "^6.6.0",
    "file-url": "^3.0.0",
    "immutable": "^4.0.0-rc.12",
    "jquery": "^3.4.1",
    "js-cookie": "^2.2.1",
    "jsonwebtoken": "^8.5.1",
    "keytar": "^4.9.0",
    "md5-file": "^4.0.0",
    "minimist": "^1.2.0",
    "moment": "^2.24.0",
    "node-localstorage": "^1.3.1",
    "node-restify-validation": "^1.3.0",
    "react": "^16.8.6",
    "react-app-rewired": "^2.1.5",
    "react-content-loader": "^4.2.1",
    "react-dom": "^16.8.6",
    "react-hot-loader": "^4.12.18",
    "react-hubspot-form": "^1.3.7",
    "react-icons": "^3.7.0",
    "react-markdown": "^4.3.1",
    "react-password-strength": "^2.4.0",
    "react-redux": "^7.0.3",
    "react-router-dom": "^5.0.0",
    "react-scripts": "^3.3.0",
    "react-toastify": "^5.1.1",
    "reactstrap": "^8.0.0",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-form": "^8.2.1",
    "redux-saga": "^1.0.2",
    "request": "^2.88.0",
    "restify": "^8.3.1",
    "restify-errors": "^7.0.0",
    "restify-jwt-community": "^1.0.12",
    "source-map-support": "^0.5.16"
  }
```

electron.webpack.json

```
{
  "whiteListedModules": [
    "react-hot-loader"
  ],
  "staticSourceDirectory": "public",
  "main": {
    "extraEntries": [
      "@/preload.js"
    ],
    "sourceDirectory": "app/main"
  },
  "renderer": {
    "sourceDirectory": "app/renderer",
    "template": "public/index.html",
    "webpackConfig": "webpack.renderer.js"
  }
}


```
webpack.renderer.js

```

const merge = require('webpack-merge')

module.exports = function(config) {
  config = merge.smart(config, {
    module: {
      rules: [
        {
          test: /\.js?$/,
          exclude: /node_modules/,
          use: ['react-hot-loader/webpack']
        }
      ]
    }
  })

  return config
}
```

![image](https://user-images.githubusercontent.com/34612659/74399516-113ab400-4de9-11ea-9b51-77d03004b5f3.png)

The error leads me to this line in node_modules/react-redux/lib/components/Provider.js

```
function Provider(_ref) {
  var store = _ref.store,
      context = _ref.context,
      children = _ref.children;
  var contextValue = (0, _react.useMemo)(function () {
```

**Comment by loopmode** [comment] 2020-02-13 06:09
I believe you have to add redux to whitelisted modules as well. Please search the issues here, we've had this one a few times already, but I think that's it.

So whenever you run into a react provider/context-related issue in webpack, chances are you have multiple reacts bundled in your app.
In electron-webpack, whitelisting a module means it will not be treated as a webpack external, and thus it will be included in the main bundle. Which is what you want here. Otherwise, redux might use "its own react", and not the "common one".

**Comment by shahkeyur** [comment] 2020-02-13 20:49
> I believe you have to add redux to whitelisted modules as well. Please search the issues here, we've had this one a few times already, but I think that's it.
> 
> So whenever you run into a react provider/context-related issue in webpack, chances are you have multiple reacts bundled in your app.
> In electron-webpack, whitelisting a module means it will not be treated as a webpack external, and thus it will be included in the main bundle. Which is what you want here. Otherwise, redux might use "its own react", and not the "common one".

Ohh damn, really. I wasted a lot of time on this. I added react-redux in whitelisted modules and it worked. Thank you very much. You are genius.

**Closed** 2020-02-13 20:49 UTC

**Comment by shahkeyur** [comment] 2020-02-18 21:37
@loopmode  That worked well. But now while building the application. Something doesn't seem to be right. It allows user to open the devtools and refresh in window. It didn't happen when I used electron-webpack for main and react-scripts for renderer. But now it doesn't seem to be production ready. Is there something to be added to make it production ready. I am trying to compile it with 'electron-webpack'. Is there something you could help me with? Thanks

**Comment by loopmode** [comment] 2020-02-18 23:27
Sounds like a separate/unrelated issue to me. Did you verify that the problem is directly related? For example, is the problem gone when you rebuild without whitelisted react-redux?

**Comment by shahkeyur** [comment] 2020-02-19 20:30
I guess it should be a new issue indeed. Removing react-redux doesn't work so it is not the problem. But even after build I get this message in console 

`Download the React DevTools for a better development experience: https://fb.me/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq`

I am not sure why react takes it as development env. Everything works while development but when I create a build it doesn't work. It doesn't give any error but doesn't seem to be work either(e.g. it doesn't show the component inside provider). I was wondering if this error is coming from the react as dependency of react-redux or it could be from the main react. I'd appreciate your help.

**Comment by loopmode** [comment] 2020-02-19 20:52
Not sure but it might be that react gives this message in general when you open the console/devtools.
If you don't see the component in the provider.. that seems to me like the "duplicate react copies" problem which you avoid by whitelisting react-redux, maybe even react itself. You could check out the instructions on https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react where you modify the installed react in node_modules to check something in the console.
BTW, just a feeling, but could it be that you are using some hot loading system, like react-hot-loader, or a babel plugin, and don't disable it in the production build?
Also, us it possible to share the code or provide a reproducible example?

**Comment by shahkeyur** [comment] 2020-02-19 22:40
@loopmode  Thanks for quick reply. Finally I was able to figure out the problem, it isn't react or react-redux. It is the react-dom.

This is the only dependency which prints "Download the react devtools..." message. For some reason my NODE_ENV is not set to production [in react-dom](https://github.com/facebook/react/blob/baff5cc2f69d30589a5dc65b089e47765437294b/packages/react-dom/npm/index.js) and that's why react-dom was using the development.js. I was able to fixit by set process.env.NODE_ENV=production. 

Well, my problem is I always want a production build for renderer, and sometimes I use test env for main after build. Is there any way I can use different NODE_ENV for main and renderer ?

**Comment by loopmode** [comment] 2020-02-20 06:37
Uh, that's a tricky question that I'm not sure I can answer. You can have manual webpack config files for both main and renderer, as described in the docs, and then set env values at the top of the config modules.

But to be honest, your approach to always run renderer in production mode - even during development - seems strange. I'd recommend to use it the way it's meant to be used - with NODE_ENV=production only in production builds - for various reasons.

**Comment by shahkeyur** [comment] 2020-02-20 15:23
After lot of debugging, it worked for me. 
electron-weboack.json
`"whiteListedModules": [
    "react-hot-loader",
    "react-redux",
    "react-dom",
    "react-router-dom",
    "redux-form"
  ]`

webpack.renderer.js```

module.exports = function (config) {
  console.log('NODE_ENV: ', process.env.NODE_ENV); // 'local'

  config = merge.smart(config, {
    mode: "production",
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          include: [/node_modules/],

          use: ['react-hot-loader/webpack']
        }
      ]
    }
  })

  return config
}
```

Yeah, I just want to use the production build for renderer in my electron builds not in the development. This seems to be  working well now. Thanks for your support. Electron-webpack helped me a lot. Looking forward for new cool features.
