### ISSUE TITLE
The decorators plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you want to use the legacy decorators semantics, you can set the 'legacy: true' option. (While processing: "base$2")

### ISSUE THREAD

**Issue by denizdogan** [electron-userland/electron-webpack#251] opened 2018-12-31 12:33 UTC
For some reason, when I try to use `@babel/plugin-proposal-decorators`, I get the error in the title. My project is based on electron-webpack-quick-start and I've tried to override the Babel configuration with my own .babelrc.js file, to no avail.

Any ideas what I can do in order for decorators to work with electron-webpack?

**Comment by aestrro** [comment] 2019-01-13 04:16
Yeah, I'm running into the same issue.

**Comment by michaeljpeake** [comment] 2019-02-22 11:21
I've hit the same issue. Any luck coming up with a fix?

**Comment by zamponotiropita** [comment] 2019-02-26 01:51
same here

**Comment by zamponotiropita** [comment] 2019-02-26 02:23
same here

**Comment by zamponotiropita** [comment] 2019-02-26 14:58
Just debugged the issue while looking by loooking into `out/main.js` line 442:
Put 
```
console.log("-------------------\n", this.type, this._configuration)
const pluginFuncs = this._configuration.module.rules[0].use.options.plugins.forEach(el => console.log("-------------------\n", el instanceof Array ? el[0].toString() : el.toString()));
```
in the end to see the resulting config.
Looks like some values the `webpack.config.js` are forced into certain values even they where set differently in my custom `webpack.config.js`. E.g. `resolve.extensions` is forced into `extensions: [ '.js', '.json', '.node', '.css' ] }`, even though I had customized that to different values.
This renders this library useless for me since the customization is limited and not clear what gets overwritten by the package.

**Comment by babinc** [comment] 2019-03-27 18:08
A fix for this yet?

**Comment by IvanGML** [comment] 2019-04-02 20:19
`"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
  		[
  			"@babel/plugin-proposal-decorators",
  			{ "legacy": true }
  		]
	  ]
  }`

it help to avoid the issue. took it from package.json

**Comment by loopmode** [comment] 2019-06-22 19:45
Sorry for coming so late to the game..but the problem is an entirely different one...

I will try to tackle it, short and long.

Short: 

You may not add `@babel/plugin-proposal-decorators` to devDependencies - you must add it to regular dependencies!!

Long:

There is an implicit mechanism in `electron-webpack` that was supposed to make working with it easy, but yet again it proves to be a footgun instead.
There is [this part of the code](https://github.com/electron-userland/electron-webpack/blob/1ddf5341924b3aac926240d77a51b72f7d2700f4/packages/electron-webpack/src/configurators/js.ts#L24-L31) that automatically adds any devDependencies that start with `@babel/preset-` or `@babel/plugin-` to the babel configuration automatically - but of course it doesn't specify any options at all. SO even if you manually added the plugin with `{"legacy": true}`, it gets added again and without the option, which leads to the problem.

The idea was that users simply add babel stuff to their devDependencies and it magically just works. 
In our/my defense: this was at a time when users had almost no control over webpack config, and this mechanism seemed reasonable as it actually allowed users to use babel plugins. (I myself added the "feature" back then because I needed exactly this: decorators for my app...)

Of course it was naive - mostly because I did not consider that some babel plugins might need options.. But also because implicit is always worse than explicit. I don't know how often I need to learn that lesson.

As you can see in the linked code, we do exclude some specific plugins from this mechanism. 
We could exclude the decorators plugin there as well - actually, I will do just that and release it with an upcoming version. 

But maybe we should just get rid of this implicit magic altogether - I think that nowerdays, it's entirely obsolete.

---

So, as things are now, what you can do is to add `@babel/plugin-proposal-decorators` as a regular dependency. The mechanism only looks up devDependencies, so it won't find this one and it won't automatically add it to the babel config without options. 
Instead, you can add it manually - via `.babelrc`, `.babelrc.js` or in `package.json/babel` - and it will work as expected.

If you also use `@babel/plugin-proposal-class-properties`, you will then run into the next error:
```
If you are using ["@babel/plugin-proposal-decorators", { "legacy": true }], make sure it comes *before* "@babel/plugin-proposal-class-properties" and enable loose mode, like so:
        ["@babel/plugin-proposal-decorators", { "legacy": true }]
        ["@babel/plugin-proposal-class-properties", { "loose": true }]
```
But when you do as suggested, it works just fine.

Here's a working example: https://github.com/loopmode/electron-webpack-quick-start/tree/example-%40babel/plugin-proposal-decorators

**Closed by loopmode** 2019-06-22 19:45 UTC
