### ISSUE TITLE
".env is not allowed in preset options" when setting up react JSX

### ISSUE THREAD

**Issue by AlexandreKilian** [electron-userland/electron-webpack#146] opened 2018-05-12 12:00 UTC
When Following the Instructions to set up with React JSX, the application doesnt work anymore.

### Steps to reproduce

1. Follow installation Process description from quick-start: https://webpack.electron.build/
2. Add React JSX according to https://webpack.electron.build/add-ons#react-jsx
3. Start with ``yarn dev``

### Expected behavior

Everything works as described

### Actual behavior

 ERROR in ./src/renderer/index.js
 Module build failed: Error: [BABEL] ./src/renderer/index.js: .env is not allowed in preset options

### Informations

Node v8.9.4

**Comment by rdiazv** [comment] 2018-05-15 23:33
I'm having the same issue.

**Comment by SirWaddles** [comment] 2018-05-16 06:09
I think this is a duplicate of #123, you can resolve it by installing `@babel/preset-react` instead of `babel-preset-react`

**Comment by loopmode** [comment] 2018-05-16 06:31
see https://github.com/electron-userland/electron-webpack/commit/55a8942122d973e336442ec7e60137889300e82b

**Closed by loopmode** 2018-05-16 06:31 UTC

**Comment by AlexandreKilian** [comment] 2018-05-16 12:52
Ah, someone updated the docs now too :)

**Comment by loopmode** [comment] 2018-05-16 12:53
yeah, updated my previous comment to clarify that :)
